#container intended to use with volume binded to src and 

FROM rust:1

WORKDIR /app/src

RUN cargo install diesel_cli
RUN cargo install cargo-watch


ENV DATABASE_URL=/data/users.db
ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8000
ENV DEV_SERVER=1

RUN mkdir /data
VOLUME [ "/data" ]

CMD ["/app/src/start_server.sh"]
